http:
  routers:
    web-router:
      rule: "PathPrefix(`/`)"
      service: web-service
      entryPoints:
      - web

  services:
    web-service:
      loadBalancer:
        algorithm: roundrobin
        servers:
        - url: "http://ip-server:80"
        - url: "http://ip-server:80"
        healthCheck:
          path: "/"
          interval: "10s"
          timeout: "3s"
